# Generated by Django 4.2.8 on 2024-05-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvnpaydetail',
            name='order_vnpay_id',
            field=models.CharField(max_length=20),
        ),
    ]
