# Generated by Django 4.2.8 on 2024-05-13 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentProduct',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='contentShop',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
