# Generated by Django 4.2.8 on 2024-05-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_paymentvnpaydetail_order_vnpay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvnpaydetail',
            old_name='order_vnpay_id',
            new_name='order_vnpay_identified',
        ),
    ]
