# Generated by Django 4.2.8 on 2024-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
