# Generated by Django 4.2.8 on 2024-05-13 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
            preserve_default=False,
        ),
    ]
