# Generated by Django 4.2.8 on 2024-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_like_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
