# Generated by Django 4.2.8 on 2024-05-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_comment_rating_rename_rating_shop_rated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='shop',
        ),
    ]
