# Generated by Django 4.2.8 on 2024-05-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_order_vnpay_id_paymentvnpaydetail_order_vnpay_identified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvnpaydetail',
            old_name='order',
            new_name='orderEcommerce',
        ),
        migrations.RenameField(
            model_name='paymentvnpaydetail',
            old_name='order_vnpay_identified',
            new_name='order_id',
        ),
    ]
