# Generated by Django 4.2.8 on 2024-05-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_comment_shop_remove_rating_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='img',
        ),
    ]
