# Generated by Django 4.2.8 on 2024-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_replycomment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='isParentComment',
            field=models.BooleanField(default=False),
        ),
    ]
