# Generated by Django 4.2.8 on 2024-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_replycomment_isparentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
