# Generated by Django 4.2.8 on 2024-05-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_orderdetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=50)),
                ('product_images_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productimagescolors')),
            ],
        ),
    ]
