# Generated by Django 4.2.8 on 2024-05-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_orderextrafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductColorField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('product_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productimagescolors')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderExtraField',
        ),
    ]
