# Generated by Django 4.2.8 on 2024-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_rename_orderproductcolorfield_orderproductcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
